---
title: "Untitled"
author: "José Ligorría"
date: "6/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load_pack_piv = library(nnet,logical.return = T)
if(load_pack_piv==FALSE){install.packages("nnet");library(nnet,logical.return = T)}
size = 1:ncol(tcy)
skip = c(TRUE,FALSE)
maxit = c(100,500)

parms_nnet = expand.grid("size"=size,"skip"=skip,"maxit"=maxit)


```

```{r}
Resultados = NULL 

conjunto_iterador = parms_nnet
ptm = proc.time()
for (i in 1:nrow(conjunto_iterador)) {
  ptm_inicial = proc.time()
  max_val = max(dataset_s$median_house_value)*1.5
  set.seed(1)
  nnet_piv = nnet(median_house_value/max_val~.,tcy,size = conjunto_iterador$size[i],skip = conjunto_iterador$skip[i], maxit = conjunto_iterador$maxit[i])
  #print("Creada la nnet")
  pred = predict(nnet_piv,vcy)*max_val
  #print("Pasamos pred")
  Resultados_piv = data.frame(cbind("Method" = c("NNET"),"ID_Parm" = c(i),"RMSE"=mean((vcy$median_house_value - pred)**2)**0.5,"Tiempo" = (proc.time() - ptm_inicial)[3]),stringsAsFactors=F)
  #print("a")
  rownames(Resultados_piv) = i
  #print("b")
  Resultados = rbind(Resultados,Resultados_piv)
  #print("c")
  
  print(c("NNET",i,i/nrow(conjunto_iterador),"RMSE: ",Resultados_piv$RMSE,"  min RMSE: ",min(as.numeric(Resultados$RMSE)),"  Tiempo: ",Resultados_piv$Tiempo, "  Aproximado restante: ",(nrow(conjunto_iterador)-i)*mean(as.numeric(Resultados$Tiempo))  ))
  
  
}
(proc.time() - ptm)[3]
save.image("C:/Users/jose-/Documents/Maestria/Econometria_R/Proyecto/Kaggle_EconometicsR/Envs/NNET_1.RData")
```

```{r}
  best_parm = which.min(as.numeric(Resultados$RMSE))
  set.seed(1)
  nnet_final = nnet(median_house_value/max_val~.,tcy,size = conjunto_iterador$size[best_parm],skip = conjunto_iterador$skip[best_parm], maxit = conjunto_iterador$maxit[best_parm])
  
  pred_vcy = predict(nnet_final,vcy)*max_val
  RMSE_vcy = mean((vcy$median_house_value - pred_vcy)**2)**0.5
  pred_f = predict(nnet_final,dataset_f_s)*max_val
  
  pred_ttcy = predict(nnet_final,ttcy)*max_val
  RMSE_ttcy = mean((ttcy$median_house_value - pred_ttcy)**2)**0.5
  pred_f = predict(nnet_final,dataset_f_s)*max_val
  pred_f_ant = pred_f
  sum(pred_f-pred_f_ant)
  median_value = median(dataset$median_house_value)
  
  dim(pred_f) # 6129    
  dim(test) # 6193   
  pred_f[which(is.na(pred_f))] = median_value
  
  submission2 = as.data.frame(cbind(test$id,pred_f))
  colnames(submission2) = c("id"	,"median_house_value")

  write.csv(submission2,"C:/Users/jose-/Documents/Maestria/Econometria_R/Proyecto/Kaggle_EconometicsR/submission2_20200624.csv",row.names = F)
  
  summary(pred_ttcy)
  head(submission1)
```


```{r}
plot(vcy$median_house_value,pred)
```



```{r}
mean_piv = mean(dataset$median_house_value)
mean((ttcy$median_house_value - pred_ttcy)**2)**0.5

mean((ttcy$median_house_value[1:10] - pred_ttcy[1:10])**2)**0.5
```


