---
title: "Untitled"
author: "José Ligorría"
date: "6/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load_pack_piv = library(randomForest,logical.return = T)
if(load_pack_piv==FALSE){install.packages("randomForest");library(randomForest,logical.return = T)}
ntree = 10:100
mtry = c(1:10)

parms_rf = expand.grid("ntree"=ntree,"mtry"=mtry)


```

```{r}
Resultados = NULL 

ptm = proc.time()
conjunto_iterador =parms_rf
for (i in 1:nrow(conjunto_iterador)) {
  ptm_inicial = proc.time()
  set.seed(1)
  rf_piv = randomForest(median_house_value~.,tcy,ntree = conjunto_iterador$ntree[i],mtry = conjunto_iterador$mtry[i])
  #print("Creada el rf")
  pred = predict(rf_piv,vcy)
  #print("Pasamos pred")
  Resultados_piv = data.frame(cbind("Method" = c("RandomForest"),"ID_Parm" = c(i),"RMSE"=mean((vcy$median_house_value - pred)**2)**0.5,"Tiempo" = (proc.time() - ptm_inicial)[3]),stringsAsFactors=F)
  #print("a")
  rownames(Resultados_piv) = i
  #print("b")
  Resultados = rbind(Resultados,Resultados_piv)
  #print("c")
  
  print(c("rF",i,i/nrow(conjunto_iterador),"RMSE: ",Resultados_piv$RMSE,"  min RMSE: ",min(as.numeric(Resultados$RMSE)),"  Tiempo: ",Resultados_piv$Tiempo, "  Aproximado restante: ",(nrow(conjunto_iterador)-i)*mean(as.numeric(Resultados$Tiempo))  ))
  
  
}
(proc.time() - ptm)[3]
save.image("C:/Users/jose-/Documents/Maestria/Econometria_R/Proyecto/Kaggle_EconometicsR/Envs/rF_1.RData")
```

```{r}
  best_parm = which.min(as.numeric(Resultados$RMSE))
  set.seed(1)
  rf_final =  randomForest(median_house_value~.,tcy,ntree = conjunto_iterador$ntree[best_parm],mtry = conjunto_iterador$mtry[best_parm])
  
  pred_vcy = predict(rf_final,vcy)
  RMSE_vcy = mean((vcy$median_house_value - pred_vcy)**2)**0.5
  pred_f = predict(rf_final,dataset_f_s)
  
  pred_ttcy = predict(rf_final,ttcy)
  RMSE_ttcy = mean((ttcy$median_house_value - pred_ttcy)**2)**0.5
  pred_f = predict(rf_final,dataset_f_s)
  pred_f_ant = pred_f
  sum(pred_f-pred_f_ant)
  median_value = median(dataset$median_house_value)
  
  dim(pred_f) # 6129    
  dim(test) # 6193   
  pred_f[which(is.na(pred_f))] = median_value
  
  submission3 = as.data.frame(cbind(test$id,pred_f))
  colnames(submission3) = c("id"	,"median_house_value")

  write.csv(submission3,"C:/Users/jose-/Documents/Maestria/Econometria_R/Proyecto/Kaggle_EconometicsR/submission3_20200624.csv",row.names = F)
  
  summary(pred_ttcy)
  head(submission1)
```

